### ISSUE TITLE
General correspondence

### ISSUE THREAD

**Issue by tsv19su254052** [yuka0705/Trading-Bot#7]
If it's not a secret, do you have a mathematical model on which this project was written?

**Comment by yuka0705** [comment]
Yeah.
If you have Skype, then Could you contact to me?
you can see my address on GitHub profile page.

**Comment by yuka0705** [comment]
![image](https://user-images.githubusercontent.com/98655326/200917237-668015b2-2833-42e5-97fd-5aa4826371ba.png)

**Comment by yuka0705** [comment]
yeah
